version: "3.8"

services:
  es:
    image: elasticsearch:7.9.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - "xpack.security.enabled=false"
      - "USE_SSL=false"
    networks:
      - "dev-app"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
      - "elasticsearch_logs:/usr/share/elasticsearch/logs"

  redis:
    image: redis
    networks:
      - "dev-app"
    volumes:
      - "redis_data:/opt/redis/data"

  fastapi:
    build: .
    networks:
      - "dev-app"
    depends_on:
      - es
      - redis

volumes:
    elasticsearch_data:
    elasticsearch_logs:
    redis_data:

networks:
  dev-app:
